### ISSUE TITLE
Questions about sd features

### ISSUE THREAD

**Issue by sixi111** [Junyi42/sd-dino#10]
Hello, I would like to know whether the 2, 5, 8-layer features mentioned in the paper refer to the actual 2, 5, 8 layers or the layers after processing with the UpSample block. Does it mean the results obtained after the UpSample block processing? I find it a bit challenging to understand the feature extraction in the code. I hope to receive your reply. Thank you!

**Comment by sixi111** [comment]
> Hello, I would like to know whether the 2, 5, 8-layer features mentioned in the paper refer to the actual 2, 5, 8 layers or the layers after processing with the UpSample block. Does it mean the results obtained after the UpSample block processing? I find it a bit challenging to understand the feature extraction in the code. I hope to receive your reply. Thank you!

I apologize for the oversight. In your statement, the layers processed by the upsampling module refer to the layers counted from 1, specifically, layers 3, 6, and 9.

**Comment by sixi111** [comment]
> Hello, I would like to know whether the 2, 5, 8-layer features mentioned in the paper refer to the actual 2, 5, 8 layers or the layers after processing with the UpSample block. Does it mean the results obtained after the UpSample block processing? I find it a bit challenging to understand the feature extraction in the code. I hope to receive your reply. Thank you!

I'm sorry for the oversight. I found a deficiency in my expression. By the layers processed through the upsampling module, I mean the layers counted from 1, specifically, layers 3, 6, and 9.

**Comment by Junyi42** [comment]
Hi,

Thanks for your interest in our work!

The index for the layer (2, 5, 8) is parsed into the `load_model()` function in the [extractor_sd.py](https://github.com/Junyi42/sd-dino/blob/master/extractor_sd.py#L169) file and then serve as the argument `unet_block_indices` for the feature extractor.

Then, you can check the exact implementation of how the features are extracted in the file [ldm.py](https://github.com/Junyi42/sd-dino/blob/master/third_party/ODISE/odise/modeling/meta_arch/ldm.py#L389) by searching for the key `unet_block_indices`.

Hope this could be helpful and feel free to put any questions for more details!
