### ISSUE TITLE
Installation issues for Mask Former

### ISSUE THREAD

**Issue by DevikalyanDas** [Junyi42/sd-dino#11]
Hello @Junyi42 , 
Thanks for your contribution. I am facing the an installation issue when running the "pip install -e ." command. This is giving the error as follows:

Emitting ninja build file /BS/keytr_neus/work/supplementary/sd-dino/third_party/Mask2Former/build/temp.linux-x86_64-cpython-39/build.ninja...

error: [Errno 2] No such file or directory: '/BS/keytr_neus/work/supplementary/sd-dino/third_party/Mask2Former/build/temp.linux-x86_64-cpython-39/build.ninja'

ERROR: Failed building wheel for mask2former

ERROR: Could not build wheels for mask2former, which is required to install pyproject.toml-based projects

Please help me in this

**Comment by Junyi42** [comment]
Hi,

Thanks for your interest in our work!

> error: [Errno 2] No such file or directory: '/BS/keytr_neus/work/supplementary/sd-dino/third_party/Mask2Former/build/temp.linux-x86_64-cpython-39/build.ninja'

For this issue, you could check whether there exists a folder `third_party/Mask2Former/build/temp.linux-x86_64-cpython-39`, and you could create one if not. Then, rerun the `pip install -e .` command, and it might avoid this issue.

> ERROR: Could not build wheels for mask2former, which is required to install pyproject.toml-based projects

I'm sorry I haven't met this issue before. After a quick search on [Google](https://www.google.com/search?q=which+is+required+to+install+pyproject.toml-based+projects), a potential solution could be `pip install pyproject-toml` and `pip install setuptools wheel`. Hope this could address your issue.

Best.

**Comment by DevikalyanDas** [comment]
Hello, thanks for your quick reply. Yes, creating the folder in third party actually removed the error. Thanks a lot.

**Comment by guanjunwu** [comment]
if the problem still exists, just use `pip install setuptools==59.5.0`
