### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by iago-suarez** [Junyi42/sd-dino#13]
Hi,

Thanks for this awesome work! 🤩

DINO and StableDiffusion works have MIT licenses. Is your work also MIT?

Best,
Iago.

**Comment by Junyi42** [comment]
Hi Iago,

Thanks for your interest in our work!

We intend to release it under MIT, but unfortunately,  we use the implicit text embedding from [ODISE](https://github.com/NVlabs/ODISE) when extracting the SD features, which is under NVIDIA's license. We are planning to remove this part in the future and release under MIT license. 

Currently, you could use the [DIFT](https://github.com/Tsingularity/dift) implementation for SD feature extractor to replace the ODISE's version in https://github.com/Junyi42/sd-dino/blob/master/extractor_sd.py, and this way will be under MIT.

Best,
Junyi
