### ISSUE TITLE
The image size for extracting the Dinov2-pretrained-model

### ISSUE THREAD

**Issue by Dengzhi-USTC** [Junyi42/sd-dino#14]
Hi,

Thanks for this awesome work! 🤩

The image resolution is 518 in the Dinov2-pretrained-model, why you can use the 840.

looking forward your reply.

**Comment by Junyi42** [comment]
Hi,

Thanks for your interest in our work and the interesting question!

Our implementation of the Dino feature extractor follows [dino-vit-features](https://github.com/ShirAmir/dino-vit-features), which interpolates the positional encodings of ViT to support input image of different resolutions other than the original one. I believe there are more work looking into how to upsample the feature maps, e.g., the recent [FeatUp](https://arxiv.org/abs/2403.10516).

Best,
Junyi

**Comment by Dengzhi-USTC** [comment]
Thanks a lot.
