### ISSUE TITLE
miss keys

### ISSUE THREAD

**Issue by wxinhua** [Junyi42/sd-dino#17]
Hi, thank you for your great work. I follow your readme to install the environment, but meet this problem when I run the demo.

WARNING:fvcore.common.checkpoint:Keys with prefix are removed from state_dict:
backbone.feature_extractor.,category_head.clip.clip.,clip_head.clip.clip.
WARNING:fvcore.common.checkpoint:Removed 2483 ignored_state_dict keys from missing_keys

Do you know how to fix it? Thank you.

**Comment by Junyi42** [comment]
The "missing keys" is expected, and we do not use these layers in our pipeline.
