### ISSUE TITLE
Collab Demo

### ISSUE THREAD

**Issue by anas-zafar** [Junyi42/sd-dino#2]
Thank you for the amazing work! I am trying to visualize the feature maps for dino and SD. Do you have a collab notebook, that I can use to run it?

**Comment by Junyi42** [comment]
Hi there, thank you for your interest in our project!

We've provided a Jupyter notebook that allows you to visualize the feature maps of SD, DINO, and Fused features. You can find it here: [demo_vis_features.ipynb](https://github.com/Junyi42/sd-dino/blob/master/demo_vis_features.ipynb). 

By default, the notebook is set up to visualize the Fused features. If you'd like to visualize the SD features, you can do this by changing the `FUSE_DINO` variable (in the second code block) from `1` to `0`. Similarly, to visualize the DINO features, change the `ONLY_DINO` variable from `0` to `1`.

The repository should be straightforward to clone onto Google Colab. And if you encounter any issues or have any questions, please don't hesitate to reach out to us. Thanks!
