### ISSUE TITLE
Object Swapping (with refinement process)

### ISSUE THREAD

**Issue by StellarCheng** [Junyi42/sd-dino#4]
Hi Junyi,
Could you please provide the code for Object Swapping (with refinement process), current object swapping result seems blur

**Comment by Junyi42** [comment]
Hi,

Thank you for your interest in our work. We are in the process of finalizing the refinement implementation and will release it soon. We appreciate your patience.

In the meantime, you can also refer to this repo: [DiffSketch](https://github.com/Junyi42/DiffSketch), which implements image-to-image translation with SD features in the similar style of our refinement process. Specifically, you can start with either [pnp_sketch.py](https://github.com/Junyi42/DiffSketch/blob/main/pnp_sketch.py) or [pnp_sketch.ipynb](https://github.com/Junyi42/DiffSketch/blob/main/pnp_sketch.ipynb) and take the preliminary swapped image as input. Plus, you may also need to modify the prompt in [pnp_refine_all.yaml](https://github.com/Junyi42/DiffSketch/blob/main/configs/pnp_refine_all.yaml) to `"a photo of a {category_of_instance}, realistic, high resolution, high quality"`.

I hope this guidance assists you.

Best regards.

**Comment by StellarCheng** [comment]
> Hi,
> 
> Thank you for your interest in our work. We are in the process of finalizing the refinement implementation and will release it soon. We appreciate your patience.
> 
> In the meantime, you can also refer to this repo: [DiffSketch](https://github.com/Junyi42/DiffSketch), which implements image-to-image translation with SD features in the similar style of our refinement process. Specifically, you can start with either [pnp_sketch.py](https://github.com/Junyi42/DiffSketch/blob/main/pnp_sketch.py) or [pnp_sketch.ipynb](https://github.com/Junyi42/DiffSketch/blob/main/pnp_sketch.ipynb) and take the preliminary swapped image as input. Plus, you may also need to modify the prompt in [pnp_refine_all.yaml](https://github.com/Junyi42/DiffSketch/blob/main/configs/pnp_refine_all.yaml) to `"a photo of a {category_of_instance}, realistic, high resolution, high quality"`.
> 
> I hope this guidance assists you.
> 
> Best regards.

Thanks for your reply
