### ISSUE TITLE
how to fix the issue of 'RuntimeError: Panoptic/odise_label_coco_50e.py not available in Model Zoo!'

### ISSUE THREAD

**Issue by hongge831** [Junyi42/sd-dino#5]
RuntimeError: Panoptic/odise_label_coco_50e.py not available in Model Zoo!
would you mind to telling me how to fix the issue.

**Comment by hongge831** [comment]
and how to run in the offline manner, I mean how can I download the pretrained model and where to place them in a correct way?
could you please give me some advise?

**Comment by Junyi42** [comment]
> RuntimeError: Panoptic/odise_label_coco_50e.py not available in Model Zoo! would you mind to telling me how to fix the issue.

Hi,

To better assist you, could you please elaborate more about this error? Specifically: 1) how to reproduce this issue? 2) at which exact line or section of the code did this error message emerge?

As for offline usage, while I haven't explored this myself, I assume that after the checkpoints are initially downloaded when the first run, you should be able to utilize the cached model offline later.

Best.

**Comment by hongge831** [comment]
thank you for you reply,  I have fixed it.
by the way, when dose the refinement code will be released, I am also waiting for this part of code for my own project.
thanks again

**Comment by robotyingtang** [comment]
> RuntimeError: Panoptic/odise_label_coco_50e.py not available in Model Zoo! would you mind to telling me how to fix the issue.

hello, would you mind to telling me how to fix this? I have also encountered this issue.

**Comment by Junyi42** [comment]
> > RuntimeError: Panoptic/odise_label_coco_50e.py not available in Model Zoo! would you mind to telling me how to fix the issue.
> 
> hello, would you mind to telling me how to fix this? I have also encountered this issue.

Hi, 

Sorry that I haven't met a similar issue. Could you please check the path `third_party/ODISE/odise/model_zoo`? The `configs` folder should be linked to `third_party/ODISE/configs` for loading the `Panoptic/odise_label_coco_50e.py` file. You can set up a soft link or just copy the folder.

Please let me know if it works, thanks!

**Comment by Junyi42** [comment]
> thank you for you reply, I have fixed it. by the way, when dose the refinement code will be released, I am also waiting for this part of code for my own project. thanks again

Hi,

Glad to know that you were able to resolve the issue. If possible, could you share any insights or tips for this problem? It would be greatly appreciated!

Regarding the refinement code, sorry that I'm currently tied up with a few things, but I aim to have it cleaned up and released by December. In the meantime, I recommend checking out issue #4 for more detailed guidance. It should provide methods that can achieve similar results.

Thanks for your understanding and patience.

**Comment by robotyingtang** [comment]
> > > RuntimeError: Panoptic/odise_label_coco_50e.py not available in Model Zoo! would you mind to telling me how to fix the issue.
> > 
> > 
> > hello, would you mind to telling me how to fix this? I have also encountered this issue.
> 
> Hi,
> 
> Sorry that I haven't met a similar issue. Could you please check the path `third_party/ODISE/odise/model_zoo`? The `configs` folder should be linked to `third_party/ODISE/configs` for loading the `Panoptic/odise_label_coco_50e.py` file. You can set up a soft link or just copy the folder.
> 
> Please let me know if it works, thanks!

thank u for your reply, it works for  me!
