### ISSUE TITLE
ValueError: a must be greater than 0 unless no samples are taken

### ISSUE THREAD

**Issue by murmurelo111** [Junyi42/sd-dino#7]
Hi, I met the problem when I run pck_spair_pascal.py
Would you mind to telling me how to fix the issue?
Thanks!
![issue](https://github.com/Junyi42/sd-dino/assets/129838471/0c35a678-a048-405e-b7b5-f4ea898d28ec)

**Comment by murmurelo111** [comment]
![image](https://github.com/Junyi42/sd-dino/assets/129838471/bd653341-a14f-48de-a6ef-d8e235ce57fc)

**Comment by Junyi42** [comment]
Hi @murmurelo111,

Could you share how many samples (the `--SAMPLE` argument) you are using currently? It looks like this error is due to trying to randomly sample 0 pairs, which should be avoided by [this line](https://github.com/Junyi42/sd-dino/blob/master/pck_spair_pascal.py#L51).

Thanks.

**Comment by murmurelo111** [comment]
> Hi @murmurelo111,
> 
> Could you share how many samples (the `--SAMPLE` argument) you are using currently? It looks like this error is due to trying to randomly sample 0 pairs, which should be avoided by [this line](https://github.com/Junyi42/sd-dino/blob/master/pck_spair_pascal.py#L51).
> 
> Thanks.

I uesd 20
![image](https://github.com/Junyi42/sd-dino/assets/129838471/af61bd52-0fa8-470d-9c44-01a4b4292510)

**Comment by Junyi42** [comment]
Hi @murmurelo111,

Thanks for the info. According to [this issue](https://github.com/Alfred1984/interesting-python/issues/10), it is most likely that the `pairs` list is empty. Please check whether you have set the path to the dataset correctly.

Best.

**Comment by murmurelo111** [comment]
> Hi @murmurelo111,
> 
> Thanks for the info. According to [this issue](https://github.com/Alfred1984/interesting-python/issues/10), it is most likely that the `pairs` list is empty. Please check whether you have set the path to the dataset correctly.
> 
> Best.

Thanks for reply!  I have solved the problem by changing `pairs = sorted(glob(f'{path}/PairAnnotation/{split}/*:{category}.json'))` to `pairs = sorted(glob(f'{path}/PairAnnotation/{split}/*_{category}.json'))`
